name: use actions

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mayank Maurya' 
      - name: Log time of the action
        run: echo "${{ steps.greet.outputs.time }}"
      - name: list contents before checkout
        run: |
          pwd
          ls -ltra
      - name: checkout code from github
        uses: actions/checkout@v1
      - name: list contents after checkout
        run: |
          pwd
          ls -ltra
