name: shell commands

on : [pull, push]

runs-on: ununtu-latest
  jobs:
    - name: execute shell commands
      run: echo "hello Worlds"
    - name: multiline strings
      run: |
        node -v
        npm -v
