name: shell commands

on : [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: execute shell commands
        run: echo "hello Worlds"
      - name: multiline string
        run: |
          node -v
          npm -v
      - name: run a command on a python shell
        run: |
          import platform
          print(platform.processor())
        shell: python
